apiVersion: v1
kind: Namespace
metadata:
  name: openspeedtest
  labels:
    name: openspeedtest

---

apiVersion: apps/v1
kind: Deployment
namespace: openspeedtest
metadata:
  name: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: openspeedtest/latest:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
namespace: openspeedtest
metadata:
  name: openspeedtest
spec:
  type: NodePort
  selector:
    app: openspeedtest
  ports:
    - port: 3000
      targetPort: 3000
